/*Creacion de tablas*/


--------------------------------------------------TIPO ESTADOS

CREATE TABLE ESTADO(

    OID_ESTADO INT UNIQUE NOT NULL,
    TIPO VARCHAR(20)
);
    
INSERT INTO ESTADO VALUES (1,'FINALIZADO');
INSERT INTO ESTADO VALUES (2,'EN_CURSO');
INSERT INTO ESTADO VALUES (3,'PENDIENTE');
INSERT INTO ESTADO VALUES (4,'STAND_BY');

--------------------------------------------------TIPO DURACION

--DROP TABLE DURACION;
CREATE TABLE DURACION(

    OID_DURACION INT UNIQUE NOT NULL,
    TIPO VARCHAR(20)

);
    
INSERT INTO DURACION VALUES (1,'CORTO');
INSERT INTO DURACION VALUES (2,'MEDIO');
INSERT INTO DURACION VALUES (3,'LARGO');

--------------------------------------------------CLIENTE

CREATE TABLE CLIENTE(

    OID_CLIENTE NUMBER(7) NOT NULL,
    NICKNAME VARCHAR(16) NOT NULL,
    DNI VARCHAR(9) NOT NULL,
    PRIMARY KEY (OID_CLIENTE), 
    UNIQUE(NICKNAME),
    CONTRASEÑA VARCHAR(16),
    NOMBRE VARCHAR(25),
    APELLIDOS VARCHAR(25),
    FECHA_NACIMIENTO DATE,
    TELEFONO NUMBER(9) NOT NULL,
    CORREO VARCHAR(40)

);

CREATE TABLE EMPLEADO(

    OID_EMPLEADO NUMBER(7) NOT NULL,
    NICKNAME VARCHAR(16) NOT NULL,
    DNI VARCHAR(9),
    PRIMARY KEY(OID_EMPLEADO),
    UNIQUE(NICKNAME),
    CONTRASEÑA VARCHAR(16),
    NOMBRE VARCHAR(25),
    APELLIDOS VARCHAR(25),
    FECHA_NACIMIENTO DATE,
    TELEFONO NUMBER(9),
    CORREO VARCHAR(40) 
 
);

CREATE TABLE PROYECTO(

    OID_PROYECTO NUMBER(7),
    NOMBRE VARCHAR(20) NOT NULL,
    PRIMARY KEY(OID_PROYECTO),
    UNIQUE(NOMBRE),
    DESCRIPCION VARCHAR(100),
    FECHA_INICIO DATE,
    FECHA_FINAL DATE,
    VALORACION INT,
    DURACION INT,
    NUMPLAZOS NUMBER(1),
    ESTADO NUMBER(1),
    PERMISO CHAR(1)DEFAULT 'Y',
    OID_CLIENTE INT,
    OID_EMPLEADO INT,
    FOREIGN KEY (OID_EMPLEADO) REFERENCES EMPLEADO(OID_EMPLEADO),
    FOREIGN KEY (OID_CLIENTE) REFERENCES CLIENTE(OID_CLIENTE),
    FOREIGN KEY (ESTADO) REFERENCES ESTADO(OID_ESTADO),
    FOREIGN KEY (DURACION) REFERENCES DURACION(OID_DURACION)

);

CREATE TABLE Mueble(
      
      oid_mueble number(7),
      PRIMARY KEY(oid_mueble),
      nombreMueble varchar(16),
      descripcion varchar(100),
      precio decimal,
      imagen varchar(64),
      stock integer default 0
      
);

CREATE TABLE Venta(

      oid_venta number(7),
      PRIMARY KEY(oid_venta),      
      nickname_cliente varchar(16),
      fechaCompra date DEFAULT CURRENT_DATE,
      precioTotal number(8,2),
      numPlazos integer,
      FOREIGN KEY (nickname_cliente) REFERENCES Cliente(NICKNAME)
      
);
      
CREATE TABLE Carrito(

      nickname_cliente varchar(16),
      nombreMueble varchar(25),
      cantidad integer,
      precio number(8,2),
      FOREIGN KEY (nickname_cliente) REFERENCES Cliente(NICKNAME),
      FOREIGN KEY (nombreMueble) REFERENCES Mueble(nombreMueble)
);

ALTER TABLE Cliente MODIFY (DNI NOT NULL);
ALTER TABLE Cliente MODIFY (oid_cliente NOT NULL);
ALTER TABLE Cliente MODIFY (contraseña NOT NULL);
ALTER TABLE Cliente MODIFY (nickname_cliente NOT NULL);
ALTER TABLE Cliente MODIFY (nombre NOT NULL);
ALTER TABLE Cliente MODIFY (apellidos NOT NULL);
ALTER TABLE Cliente MODIFY (correo NOT NULL);
ALTER TABLE Cliente MODIFY (numTelefono NOT NULL);

ALTER TABLE Empleado MODIFY (nickname_empleado NOT NULL);
ALTER TABLE Empleado MODIFY (oid_empleado NOT NULL);
ALTER TABLE Empleado MODIFY (contraseña NOT NULL);
ALTER TABLE Empleado MODIFY (DNI NOT NULL);
ALTER TABLE Empleado MODIFY (nombre NOT NULL);
ALTER TABLE Empleado MODIFY (apellidos NOT NULL);
ALTER TABLE Empleado MODIFY (numTelefono NOT NULL);
ALTER TABLE Empleado MODIFY (correo NOT NULL);


ALTER TABLE Proyecto MODIFY  (nombre NOT NULL);
ALTER TABLE Proyecto MODIFY  (descripcion NOT NULL);
ALTER TABLE Proyecto MODIFY  (fechaInicio NOT NULL);
ALTER TABLE Proyecto MODIFY  (codigo NOT NULL);
ALTER TABLE Proyecto MODIFY  (duracion NOT NULL);
ALTER TABLE Proyecto MODIFY  (numPlazos NOT NULL);
ALTER TABLE Proyecto MODIFY  (estado NOT NULL);
ALTER TABLE Proyecto MODIFY  (nickname_cliente NOT NULL);
ALTER TABLE Proyecto MODIFY  (fianza  NOT NULL);

ALTER TABLE Mueble MODIFY  (nombreMueble NOT NULL);
ALTER TABLE Mueble MODIFY  (descripcion NOT NULL);
ALTER TABLE Mueble MODIFY  (precio NOT NULL);
ALTER TABLE Mueble MODIFY  (imagen NOT NULL);
ALTER TABLE Mueble MODIFY  (stock NOT NULL);


ALTER TABLE Venta MODIFY   (nickname_cliente  NOT NULL);
ALTER TABLE Venta MODIFY   (fechaCompra NOT NULL);
ALTER TABLE Venta MODIFY   (nombreMueble  NOT NULL);
ALTER TABLE Venta MODIFY   (cantidadMueble  NOT NULL);
ALTER TABLE Venta MODIFY   (precioTotal  NOT NULL);
ALTER TABLE Venta MODIFY   (numPlazos  NOT NULL);


ALTER TABLE Carrito MODIFY (nickname_cliente  NOT NULL);
ALTER TABLE Carrito MODIFY (nombreMueble NOT NULL);
ALTER TABLE Carrito MODIFY (cantidad NOT NULL);
ALTER TABLE Carrito MODIFY (precio NOT NULL);

ALTER TABLE CLIENTE ADD CONSTRAINT CK_DNI_CLIENTE CHECK (REGEXP LIKE(DNI, '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]'));
ALTER TABLE CLIENTE ADD CONSTRAINT CK_NUM_CLIENTE CHECK (REGEXP LIKE(numTelefono, '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'));
ALTER TABLE EMPLEADO ADD CONSTRAINT CK_DNI_EMPLEADO CHECK (REGEXP LIKE(DNI, '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][A-Z]'));
ALTER TABLE EMPLEADO ADD CONSTRAINT CK_NUM_EMPLEADO CHECK (REGEXP LIKE(numTelefono, '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'));
ALTER TABLE PROYECTO ADD CONSTRAINT CK_VALORACION CHECK (Valoracion IN ('1','2','3','4','5');
ALTER TABLE PROYECTO ADD CONSTRAINT CK_NUMPLAZOS CHECK (NUMPLAZOS IN ('1','2','4');
ALTER TABLE PROYECTO ADD CONSTRAINT CK_FECHA CHECK (TO_DATE(FECHA_INICIO, 'DD/MM/YYYY') < TO_DATE(FECHA_FINAL,'DD/MM/YYYY'));

--------------------------------------------
/*SECUENCIAS*/

CREATE SEQUENCE INCRE_OID_PROYECTO
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 999999
  CYCLE;

CREATE SEQUENCE INCRE_OID_EMPLEADO
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 999999
  CYCLE;

CREATE SEQUENCE INCRE_OID_CLIENTE
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 999999
  CYCLE;


CREATE SEQUENCE INCRE_OID_MUEBLE --DROP SEQUENCE INCRE_OID_MUEBLE;
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 999999
  CYCLE;

CREATE SEQUENCE INCRE_OID_VENTA --DROP SEQUENCE INCRE_OID_VENTA;
  INCREMENT BY 1
  START WITH 1
  MAXVALUE 999999
  CYCLE;
---------------------------------------------
/*TRIGGERS*/

CREATE OR REPLACE TRIGGER GENERA_PK_CLIENTE_AI
BEFORE INSERT ON CLIENTE
FOR EACH ROW
 DECLARE
 I INT;
BEGIN
 SELECT COUNT(*) INTO I FROM CLIENTE WHERE NICKNAME=:NEW.NICKNAME;
 IF I=0 THEN SELECT INCRE_OID_CLIENTE.NEXTVAL INTO :NEW.OID_CLIENTE FROM DUAL;
 ELSE SELECT OID_CLIENTE INTO :NEW.OID_CLIENTE FROM CLIENTE WHERE NICKNAME=:NEW.NICKNAME;
 END IF;
END;

CREATE OR REPLACE TRIGGER GENERA_PK_EMPLEADO_AI
BEFORE INSERT ON EMPLEADO
FOR EACH ROW
BEGIN
  SELECT INCRE_OID_EMPLEADO.NEXTVAL INTO :NEW.OID_EMPLEADO FROM DUAL;
END;

CREATE OR REPLACE TRIGGER GENERA_PK_PROYECTO_AI
BEFORE INSERT ON PROYECTO
FOR EACH ROW
BEGIN
 SELECT INCRE_OID_PROYECTO.NEXTVAL INTO :NEW.OID_PROYECTO FROM DUAL;
END;

CREATE OR REPLACE TRIGGER GENERA_PK_MUEBLE_AI
BEFORE INSERT ON MUEBLE
FOR EACH ROW
BEGIN
 SELECT INCRE_OID_MUEBLE.NEXTVAL INTO :NEW.OID_MUEBLE FROM DUAL;
END;

CREATE OR REPLACE TRIGGER GENERA_PK_VENTA_AI
BEFORE INSERT ON VENTA
FOR EACH ROW
BEGIN
 SELECT INCRE_OID_VENTA.NEXTVAL INTO :NEW.OID_VENTA FROM DUAL;
 SELECT CURRENT_DATE INTO :NEW.FECHACOMPRA FROM DUAL;
END;
